becool_profil:
    resource: "@BecoolProfilBundle/Controller/"
    type:     annotation
    prefix:   /profil

becool_main:
    resource: "@BecoolMainBundle/Controller/"
    type:     annotation
    prefix:   /profil
    
login:
    pattern:    /login
    defaults:    { _controller: BecoolMainBundle:Security:login }
    
login_check:
    pattern:   /profil/login_check

logout:
    pattern:   /logout