jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        in_memory:
            memory:
              users:
                admin: { password: af6c4bb9c4c90a8f02b00c8bb7aa4591b79267d8, roles: 'ROLE_ADMIN' }
                
        administrators:
            entity: { class: BecoolMainBundle:User }
            
    encoders:
        Becool\MainBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
            
        Symfony\Component\Security\Core\User\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    firewalls:
        login_firewall:
            pattern: ^/login
            anonymous: true    
        admin_area:
            pattern:    ^/admin
            provider: in_memory
            form_login:
                login_path: /login
                check_path: /admin/login_check
                default_target_path: /admin/user
            logout:
                path: logout
                target: /

    access_control:
        - { path: ^/login/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin, roles: [IS_AUTHENTICATED_FULLY,IS_AUTHENTICATED_REMEMBERED]}