jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:        
        users:
            entity: { class: Becool\Bundle\MainBundle\Entity\User, property: "username" }
            
    encoders:
        Becool\Bundle\MainBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
        Symfony\Component\Security\Core\User\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    firewalls:
        profil_area:
            pattern:    ^/profil
            provider: users
            form_login:
                login_path: /login
                check_path: /profil/login_check
                default_target_path: /profil
            logout:
                path: logout
                target: /login
        login_firewall:
            pattern: ^/login
            anonymous: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profil, roles: [IS_AUTHENTICATED_FULLY,IS_AUTHENTICATED_REMEMBERED] }